### PR TITLE
Add missing user object to server response

### LINKED ISSUE #35: Error when trying to access /login as a logged in user
menu.ejs:32
`32|                         <% if (user.canEdit) { %>`

user is not defined

### PR DESCRIPTION
**Pull request by adrianz-kainos**
Resolves #35

### CODE REVIEW

**Comment by gpimblott** [comment]
Why did it need the user object ?

**Comment by adrianz-kainos** [comment]
@gpimblott The index.ejs page (to which we redirect if a logged-in user tries to go to /login) uses menu.ejs which needs the user object to display his username, check his permissions, etc.

**Comment by xjedam** [comment]
Any reason why we let people access that page when we are already logged in? Perhaps we could just redirect a person to the main page?

**Comment by adrianz-kainos** [comment]
> Any reason why we let people access that page when we are already logged in?

Just to clarify this issue: it can occur when a user presses the back button too many times in his browser and lands on the /login page after logging in. It happened to me a few times by accident and was also pointed out by Michal Piatek one time.

> Perhaps we could just redirect a person to the main page?

I guess that was the original intent here.
`res.redirect()` is even simpler than `res.render()` and does exactly what we want. I'll prepare a new commit.

**Pull request merged**
